FROM gcr.io/distroless/base@sha256:a26dde6863dd8b0417d7060c990abe85c1d2481541568445e82b46de9452cf0c
LABEL maintainer="carsten.zeumer@autonubil.de"

WORKDIR /

ENV SNMP_COMMUNITY="public"
ENV SNMP_RETRIES=1
ENV SNMP_VERSION="v1"
ENV SNMP_TRAP_ADDRESS="localhost:162"
ENV WEBHOOK_ADDRESS="0.0.0.0:9099"
ENV LOGLEVEL=2
ENV PROMETHEUS="true"

EXPOSE 9099
EXPOSE 9350

COPY prometheus-webhook-snmptrapper /prometheus-webhook-snmptrapper
COPY sample-alert.json /

CMD exec /prometheus-webhook-snmptrapper --loglevel=$LOGLEVEL --prometheus=$PROMETHEUS --snmpversion=$SNMP_VERSION--snmpcommunity=$SNMP_COMMUNITY --snmpretries=$SNMP_RETRIES --snmptrapaddress=$SNMP_TRAP_ADDRESS --webhookaddress=$WEBHOOK_ADDRESS
